            model_type: yolov9c.pt
pretrained: True
seed: 0
imgsz: 640
batch: 8
epochs: 10
optimizer: Adam # other choices=['SGD', 'Adam', 'AdamW', 'RMSProp']
lr0: 0.01  # learning rate
name: 'yolov9c_exp_v0' # experiment name
